# .github/workflows/ci.yml
name: CI Action

on:
  push:
    branches: ["main"]

jobs:
  frontend-ci:
    uses: Smokey-Olive/main-service/.github/reusable-workflows/frontend-ci.yml
    with:
      service-name: "main-service"
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}

  server-ci:
    uses: Smokey-Olive/main-service/.github/reusable-workflows/server-ci.yml
    with:
      service-name: "main-service"
    secrets:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
