# .github/workflows/pull_request.yml
name: Pull Request Action

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  frontend-pr-check:
    uses: Smokey-Olive/main-service/.github/workflows/reusable-frontend-pr-check.yml
    with:
      service-name: "main-service"

  server-pr-check:
    uses: Smokey-Olive/main-service/.github/workflows/reusable-server-pr-check.yml
    with:
      service-name: "main-service"
